const clashroyale = [
'Arqueras',
'Caballero',
'Gigante',
'Mini P.E.K.K.A',
'Bombardero',
'Duendes',
'Duendes con Lanza',
'Reclutas Reales',
'Esqueletos',
'Esbirros',
'Horda de Esbirros',
'Valquiria',
'Mosquetera',
'Príncipe',
'Príncipe Oscuro',
'Caballero Dorado',
'Bebé Dragón',
'Dragón Infernal',
'Dragón Eléctrico',
'Gólem',
'Gólem de Hielo',
'Gólem de Elixir',
'Montapuercos',
'Choza de Bárbaros',
'Bárbaros',
'Flechas',
'Bola de Fuego',
'Rayo',
'Descarga',
'Cohete',
'Tronco',
'Bola de Nieve',
'Veneno',
'Furia',
'Tornado',
'Espirítu de Hielo',
'Espirítu de Fuego',
'Espirítu Eléctrico',
'Espirítu Sanador',
'Duquesa de dagas',
'Torre Infernal',
'Torre Tesla',
'Mortero',
'Ballesta',
'Cañonero',
'Cañón',
'Cañón con Ruedas',
'Choza de Duendes',
'Cocinero real',
'Recolector de Elixir',
'Jaula del Forzudo',
'P.E.K.K.A',
'Megacaballero',
'Megaesbirro',
'Esqueleto Gigante',
'Gigante Noble',
'Leñador',
'Montacarneros',
'Puercos Reales',
'Bandida',
'Fantasma real',
'Princesa',
'Princesa de torre',
'Cazador',
'Chispitas',
'Bruja',
'Bruja Nocturna',
'Bruja madre',
'Guardias',
'Dragones Esqueleto',
'Sabueso de Lava',
'Globo',
'Barril de Duendes',
'Barril de Esqueletos',
'Barril de Bárbaro',
'Cementerio',
'Ejército de Esqueletos',
'Minero',
'Excavadora duendes',
'Bandida',
'Zappies',
'Mago Eléctrico',
'Mago de Hielo',
'Mago',
'Arquero Mágico',
'Pillos',
'Duende Lanzadardos',
'Espejo',
'Monje',
'Gigante Rúnica',
'Berserker',
'Bandida Líder',
'Demoledor Duende',
'Fénix',]